// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    account_kpis: {
        name: "account_kpis";
        parameters: {
          /** INT - use sql.int() */
          accountId: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType INT */
          account_id: number;
          /** @sqlType STRING */
          account_name: string;
          /** @sqlType STRING */
          customer_group: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          segment: string;
          /** @sqlType STRING */
          process_node: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType BIGINT */
          installed_base: number;
          /** @sqlType BIGINT */
          new_installs_6mo: number;
          /** @sqlType DOUBLE */
          avg_utilization: number;
          /** @sqlType BIGINT */
          at_risk_tools: number;
          /** @sqlType DOUBLE */
          avg_renewal_risk: number;
          /** @sqlType BIGINT */
          l12m_revenue: number;
          /** @sqlType BIGINT */
          l12m_prior: number;
          /** @sqlType BIGINT */
          ytd_actual: number;
          /** @sqlType BIGINT */
          prior_month_actual: number;
          /** @sqlType BIGINT */
          l12m_spares: number;
          /** @sqlType BIGINT */
          l12m_labor: number;
          /** @sqlType DOUBLE */
          yoy_pct: number;
          /** @sqlType BIGINT */
          current_month_fc: number;
          /** @sqlType BIGINT */
          next6_total: number;
          /** @sqlType BIGINT */
          variance_vs_prior: number;
          /** @sqlType DOUBLE */
          variance_pct: number;
          /** @sqlType STRING */
          forecast_confidence: string;
        }>;
      };
    accounts_list: {
        name: "accounts_list";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType INT */
          account_id: number;
          /** @sqlType STRING */
          account_name: string;
          /** @sqlType STRING */
          customer_group: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          segment: string;
          /** @sqlType STRING */
          process_node: string;
        }>;
      };
    drivers: {
        name: "drivers";
        parameters: {
          /** INT - use sql.int() */
          accountId: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType DOUBLE */
          install_base_growth_pct: number;
          /** @sqlType DOUBLE */
          spares_price_uplift_pct: number;
          /** @sqlType DOUBLE */
          contract_renewal_rate_pct: number;
          /** @sqlType DOUBLE */
          labor_rate_uplift_pct: number;
          /** @sqlType INT */
          new_tool_installs_6mo: number;
        }>;
      };
    forecast_series: {
        name: "forecast_series";
        parameters: {
          /** INT - use sql.int() */
          accountId: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month_label: string;
          /** @sqlType STRING */
          month_start: string;
          /** @sqlType BIGINT */
          total_revenue_forecast: number;
          /** @sqlType BIGINT */
          total_revenue_lower: number;
          /** @sqlType BIGINT */
          total_revenue_upper: number;
        }>;
      };
    latest_submission: {
        name: "latest_submission";
        parameters: {
          /** INT - use sql.int() */
          accountId: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          confidence: string;
          /** @sqlType STRING */
          submitted_by: string;
          /** @sqlType STRING */
          submitted_at: string;
          /** @sqlType BIGINT */
          next6_forecast: number;
          /** @sqlType STRING */
          forecast_month: string;
          /** @sqlType STRING */
          version_id: string;
        }>;
      };
    monthly_revenue: {
        name: "monthly_revenue";
        parameters: {
          /** INT - use sql.int() */
          accountId: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          month_label: string;
          /** @sqlType STRING */
          month_start: string;
          /** @sqlType BIGINT */
          total_revenue: number;
          /** @sqlType BIGINT */
          spares_revenue: number;
          /** @sqlType BIGINT */
          labor_revenue: number;
          /** @sqlType BIGINT */
          contract_revenue: number;
          /** @sqlType BIGINT */
          active_tools: number;
          /** @sqlType BIGINT */
          revenue_per_tool: number;
        }>;
      };
    portfolio: {
        name: "portfolio";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType INT */
          account_id: number;
          /** @sqlType STRING */
          account_name: string;
          /** @sqlType STRING */
          customer_group: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          segment: string;
          /** @sqlType BIGINT */
          installed_base: number;
          /** @sqlType BIGINT */
          l12m_revenue: number;
          /** @sqlType BIGINT */
          next6_total: number;
          /** @sqlType DOUBLE */
          yoy_pct: number;
          /** @sqlType STRING */
          forecast_confidence: string;
          /** @sqlType BIGINT */
          at_risk_tools: number;
        }>;
      };
    versions: {
        name: "versions";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          version_id: string;
          /** @sqlType STRING */
          version_label: string;
          /** @sqlType STRING */
          status: string;
        }>;
      };
  }
}
